_wandb:
    value:
        cli_version: 0.21.1
        e:
            9g733d6lgu5oacn07gxoeyic79pwswls:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "17179869184"
                args:
                    - --model_export
                    - model_export:latest
                    - --test_data
                    - data_test.csv:latest
                codePath: evaluate/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "478601715712"
                email: IIMOAAFA@GMAIL.COM
                executable: /opt/anaconda3/envs/mlflow-d61912ba0487a9b37772c151900aeea981898558/bin/python
                git:
                    commit: d773f8915054e7067b0be2e8018f6db5a8d56677
                    remote: https://github.com/Abdulaziz-Moafa/genre_classification.git
                host: Mac-Amoafa.local
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit-Mach-O
                program: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/evaluate/run.py
                python: CPython 3.13.5
                root: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/evaluate
                startedAt: "2025-08-26T12:38:18.208301Z"
                writerId: 9g733d6lgu5oacn07gxoeyic79pwswls
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.5
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
