_wandb:
    value:
        cli_version: 0.21.1
        e:
            gv99nuine9ve1og3njgwj0bb54xlreaa:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "17179869184"
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "477829779456"
                email: IIMOAAFA@GMAIL.COM
                executable: /opt/anaconda3/envs/mlflow-4d13597ed0443924acacbd90bdc85c91cac87c1c/bin/python3.13
                git:
                    commit: d773f8915054e7067b0be2e8018f6db5a8d56677
                    remote: https://github.com/Abdulaziz-Moafa/genre_classification.git
                host: Mac-Amoafa.local
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit-Mach-O
                program: /opt/anaconda3/envs/mlflow-4d13597ed0443924acacbd90bdc85c91cac87c1c/bin/pytest
                python: CPython 3.13.5
                root: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/check_data
                startedAt: "2025-08-26T12:34:36.501563Z"
                writerId: gv99nuine9ve1og3njgwj0bb54xlreaa
        m: []
        python_version: 3.13.5
        t:
            "4": 3.13.5
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
