_wandb:
    value:
        cli_version: 0.21.1
        e:
            8rjafv8e768t9u7wodxac03rshg1gual:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "17179869184"
                args:
                    - --input_artifact
                    - preprocessed_data.csv:latest
                    - --artifact_root
                    - data
                    - --artifact_type
                    - segregated_data
                    - --test_size
                    - "0.3"
                    - --random_state
                    - "42"
                    - --stratify
                    - genre
                codePath: segregate/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "478593036288"
                email: IIMOAAFA@GMAIL.COM
                executable: /opt/anaconda3/envs/mlflow-6457425097cbd4c3e8e55b3f9622eec76fea58bd/bin/python
                git:
                    commit: d773f8915054e7067b0be2e8018f6db5a8d56677
                    remote: https://github.com/Abdulaziz-Moafa/genre_classification.git
                host: Mac-Amoafa.local
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit-Mach-O
                program: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/segregate/run.py
                python: CPython 3.13.5
                root: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/segregate
                startedAt: "2025-08-26T12:44:14.890205Z"
                writerId: 8rjafv8e768t9u7wodxac03rshg1gual
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.5
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
