_wandb:
    value:
        cli_version: 0.21.1
        e:
            lstdmh3tg195fcwups7uv38i4ql6x8om:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "17179869184"
                args:
                    - --train_data
                    - data_train.csv:latest
                    - --model_config
                    - /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/outputs/2025-08-26/15-33-39/random_forest_config.yml
                    - --export_artifact
                    - model_export
                    - --random_seed
                    - "42"
                    - --val_size
                    - "0.3"
                    - --stratify
                    - genre
                codePath: random_forest/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "478329384960"
                email: IIMOAAFA@GMAIL.COM
                executable: /opt/anaconda3/envs/mlflow-d53a6acb73467b0e223e15455db910c823f8fea0/bin/python
                git:
                    commit: d773f8915054e7067b0be2e8018f6db5a8d56677
                    remote: https://github.com/Abdulaziz-Moafa/genre_classification.git
                host: Mac-Amoafa.local
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit-Mach-O
                program: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/random_forest/run.py
                python: CPython 3.13.5
                root: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/random_forest
                startedAt: "2025-08-26T12:36:55.412651Z"
                writerId: lstdmh3tg195fcwups7uv38i4ql6x8om
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.5
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
export_artifact:
    value: model_export
features:
    value:
        categorical:
            - time_signature
            - key
        nlp:
            - text_feature
        numerical:
            - danceability
            - energy
            - loudness
            - speechiness
            - acousticness
            - instrumentalness
            - liveness
            - valence
            - tempo
            - duration_ms
random_forest:
    value:
        bootstrap: true
        ccp_alpha: 0
        class_weight: balanced
        criterion: gini
        max_depth: 13
        max_features: null
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0
        n_estimators: 100
        n_jobs: null
        oob_score: false
        random_state: 42
        verbose: 0
        warm_start: false
tfidf:
    value:
        max_features: 10
