_wandb:
    value:
        cli_version: 0.21.1
        e:
            o96i3qmb1q2jfirzdumgkeb8ousdt446:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "17179869184"
                args:
                    - --file_url
                    - https://github.com/udacity/nd0821-c2-build-model-workflow-exercises/blob/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?raw=true
                    - --artifact_name
                    - raw_data.parquet
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - Data as downloaded
                codePath: download/download_data.py
                codePathLocal: download_data.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "477663404032"
                email: IIMOAAFA@GMAIL.COM
                executable: /opt/anaconda3/envs/mlflow-208785c53130c504914c054e6968ef41300b565c/bin/python
                git:
                    commit: d773f8915054e7067b0be2e8018f6db5a8d56677
                    remote: https://github.com/Abdulaziz-Moafa/genre_classification.git
                host: Mac-Amoafa.local
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit-Mach-O
                program: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/download/download_data.py
                python: CPython 3.13.5
                root: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/download
                startedAt: "2025-08-26T12:33:42.579094Z"
                writerId: o96i3qmb1q2jfirzdumgkeb8ousdt446
        m: []
        python_version: 3.13.5
        t:
            "3":
                - 2
            "4": 3.13.5
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
